# Generated by Django 4.2.7 on 2023-11-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Add",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("depth", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("tel", models.CharField(default="", max_length=15)),
                ("homepage", models.CharField(default="", max_length=100)),
                (
                    "add1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="add1_set",
                        to="backend.add",
                    ),
                ),
                (
                    "add2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="add2_set",
                        to="backend.add",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("playDate", models.CharField(default="", max_length=15)),
                ("grade", models.IntegerField()),
                ("level", models.IntegerField()),
                ("success", models.BooleanField()),
                ("extraTime", models.CharField(default="", max_length=20, null=True)),
                (
                    "remainingTime",
                    models.CharField(default="", max_length=20, null=True),
                ),
                ("userHint", models.IntegerField(default=0, null=True)),
                ("content", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("intro", models.CharField(max_length=150)),
                ("level", models.IntegerField()),
                ("recommendPerson", models.IntegerField()),
                ("tool", models.IntegerField()),
                ("activity", models.IntegerField()),
                ("time", models.IntegerField()),
                ("grade", models.FloatField()),
                ("thumbnail", models.CharField(max_length=150)),
                ("createdAt", models.CharField(max_length=15)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_cat_set",
                        to="backend.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_set",
                        to="backend.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewKeyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rev_keyword_set",
                        to="backend.review",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rev_theme_set",
                to="backend.theme",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rev_user_set",
                to="backend.users",
            ),
        ),
    ]
