# Generated by Django 4.2.7 on 2023-11-13 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_theme_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="image",
        ),
    ]
