# Generated by Django 4.2.7 on 2023-11-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_theme_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="image",
            field=models.ImageField(default="theme/no_img.png", upload_to="theme"),
        ),
    ]
